### ISSUE TITLE
Notifications sent wrongfully months before the release. Future "updated" dates in the feed.

### ISSUE THREAD

**Issue by mzso** [alexkay/muspy#31] opened 2016-09-17 09:08 UTC
I of course forget by the time they're released. It's just annoying noise.

<del>I'm not sure if there's a proper reminder when the album is actually released. I keep missing things.</del>

Edit: So taking a closer look at the feed (I normally only view the e-mail reminders) it seems like the releases are only added once, most times with a future date.
This is bad... It makes the notifications useles

It would make sense to have two kinds of reminders just like how videoeta does, and you could choose which of them you want.

**Comment by mzso** [comment] 2016-09-17 09:22
I see this in one of the entries:
`<entry>
        <title type="text"><![CDATA[Metallica - Hardwired… to Self‐Destruct]]></title>
        <link href="https://muspy.com/releases"/>
        <id>urn:uuid:55d8ab42-990b-4c94-93c8-9ca7927b5fc0</id>
        <updated>2016-11-18T00:00:00Z</updated>
        <content type="xhtml">
            <div xmlns="http://www.w3.org/1999/xhtml">`

It was "updated" two months from now in the future.

The feed itself seems to be updated in the future: <updated>2016-10-07T00:00:00Z</updated>

**Comment by alexkay** [comment] 2016-09-17 18:10
Dupe of #9.

**Closed as completed by alexkay** 2016-09-17 18:10 UTC
